### PR TITLE
fix(tx-builder): fix contract method filtering

### LINKED ISSUE #815: tx-builder: ABI items of `error` type should not be considered as methods.
## Description

The UI does not filter ABI items correctly. 

In more detail, items whose type is `error`, which is a new kind of ABI item and can not be invoked as a method,  are also shown in the method selection box.  

Here's a sample of contract which uses such kind ABI type. https://etherscan.io/address/0xC96dE26018A54D51c097160568752c4E3BD6C364

A simple fix could be like:
```diff
-        if (e?.type?.toLowerCase() === 'event') {
+        if (e?.type?.toLowerCase() === 'event' || e?.type?.toLowerCase() === 'error' ) {
```
https://github.com/safe-global/safe-react-apps/blob/4236a28d7cc6ed5581f445ea76cc73a0d60cbec5/apps/tx-builder/src/lib/interfaceRepository.ts#L53

## Environment
 - Browser:Chrome
 - Wallet: MetaMask
 - Safe: all
 - Environment: all

## Expected result

Items like `AddressEmptyCode` should not be included in the method option box.

## Obtained result

See the screenshot below. 

## Screenshots

img

### PR DESCRIPTION
**Pull request by lmy375**
Resolves #815

### CODE REVIEW

**Comment by lmy375** [comment]
recheck

**Comment by lmy375** [comment]
recheck

**Comment by lmy375** [comment]
recheck

**Comment by lmy375** [comment]
recheck

**Comment by lmy375** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lmy375** [comment]
recheck

**Comment by lmy375** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by katspaugh — APPROVED** [review]
The code looks good, thank you! Have you tested it?

**Comment by lmy375** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lmy375** [comment]
Actually not 😢  But the patch is so simple that I believe we can skip the test?

**Comment by lmy375** [comment]
By the way I've no idea why I can not sign the CLA by comment. I'll try with another PR. This will be closed.

**Comment by katspaugh** [comment]
Please don't close it again. One PR is enough. The CLA check is fine.

**Comment by lmy375** [comment]
OK. Seems to be an issue caused by multiple git accounts. Should be fine now.

**Review by katspaugh — APPROVED** [review]

**Comment by katspaugh** [comment]
Thanks!

**Pull request merged**
