### PR TITLE
feat(safe-claiming-app): add support for investor vestings

### LINKED ISSUE #561: [Safe Claiming App] add support for investor allocations
## Overview
Investors get their tokens vested for a newly created safe.
In order to make claiming easier the claiming app should be able to fetch and display the investor allocations and be able to claim them.

## Requirements
- [ ] Fetch and display investor allocations
- [ ] Add 'claimVestedTokens' transaction for investor contract
- [ ] Remove warning "Execute at least one claim of any amount of tokens until 27.12.22 10:00 CET or your allocation will be transferred back to the SafeDAO treasury" for investor safes

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves
Adds the investor allocation to the display of claimable / vested amounts.

## Open tasks
- [x] adjust unit tests
- [x] enable transactions which only setDelegate without claiming (amount = 0)
- [x] refactor: use addresses from hosted vesting data
- [x] chore: In staging use the staging claiming app data

Resolves #561

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]
LGTM

**Comment by JagoFigueroa** [comment]
Morning! I see that the claim button is now enabled by default and I don't think that is expected :( 

Also, my delegate preferences do not seem to persist after I set one and re-enter the app. 

Here is a lil video:

https://user-images.githubusercontent.com/92332710/199435515-d77becad-926b-4097-8d71-7c3362068a9a.mp4

With the investor airdrop I see that on the revamp interface the total number of tokens to claim are present on the UI widget but in legacy web it comes as 0:

Screenshot 2022-11-02 at 08 46 37

My guess is that this is expected for now as I am checking this in legacy prod but will we need a deployment for this on the legacy web?

Cheers!

**Comment by francovenica** [comment]
I think having the button enabled is expected since you should be able to just set a delegate without claiming. That being said is not clear for the user because there is no explanation that having the field empty or putting a 0 is just setting a delegate. Also the button says "Claim and delegate".
I think we should, or make the button say just "Set delegate" if the input is empty or "0", and add in the tooltip bellow that explanation; "Leave the field empty or set it to 0 if you just want to set a new delegate"

**Comment by francovenica** [comment]
Today the claiming for "Investors" has been enabled. I was able to claim tokens just fine.
https://safe-web-core.staging.5afe.dev/gor:0x12A9ce973D9b8DA345E77Cd5D0E07186A864E1D2/transactions/tx?id=multisig_0x12A9ce973D9b8DA345E77Cd5D0E07186A864E1D2_0x0fb8afb7e604bb24801931bf7e340b412845e5c487314b7f2165413a45e3fdf7

I was also able to claim tokens with other 2 safes that are just regular users:
https://safe-web-core.staging.5afe.dev/gor:0x95ddA5dc54331a1E6B65aF1Cd7167962A2f7f280/transactions/tx?id=multisig_0x95ddA5dc54331a1E6B65aF1Cd7167962A2f7f280_0x982cc595262fa8d00b06a6b997397f3dcedb34eeb89e0afaa8229d2b931ee999

https://safe-web-core.staging.5afe.dev/gor:0x24F8542Da0C5f267c177a224270442C73804EE80/transactions/tx?id=multisig_0x24F8542Da0C5f267c177a224270442C73804EE80_0xe54006e20a542f11ab5f0ba821786fa17573b0a0c12cfa88dacfec5a56c452e3

**Comment by JagoFigueroa** [comment]
I don't know if expected caballero but the behaviour is different from the current live app, there the claim and delegate process is disabled unless a token amount is selected:

Live app, user airdrop:
Screenshot 2022-11-03 at 08 13 21

PR app, user airdrop:
Screenshot 2022-11-03 at 08 17 23


PR app, investor airdrop:
Screenshot 2022-11-03 at 08 11 35

Un abrazo

**Comment by schmanu** [comment]
@JagoFigueroa yes this is intended. 
The reason is that we want to enable investors to already delegate their voting power without having to claim tokens as token claiming will not be possible until the token is unpaused / transferable.

I fixed the last small issue with empty inputs not being accepted by treating them as zero inputs.

**Pull request merged**
