### PR TITLE
feat(mmi): Add MMI safe app

### PR DESCRIPTION
**Pull request by yagopv**
## What it solves
This PR Adds Metamask Institutional Safe App

## How to test
The app should be tested in the following networks => `mainnet`, `goerli`, `polygon`, `gnosis-chain`

Backend URL: https://safe-mmi.safe.global
Custodian environment: safe-prod

### CODE REVIEW

**Review by mikhailxyz — APPROVED** [review]

**Comment by liliya-soroka** [comment]
1. Color of the connected MM in the header is wrong
image

3.

**Comment by liliya-soroka** [comment]
The first round of testing is done . The issues are reported in the MMI-integration channel. The team works on the fixes

**Comment by liliya-soroka** [comment]
The message and connected to the safe app MMI account address were added to the MMI safe apps UI till the problem with the connection to the safe-app is solved on MMI extension side:
image

**Comment by liliya-soroka** [comment]
MMI safe app is checked and apporved

**Pull request merged**
