### PR TITLE
feat(tx-builder): Add dark mode support

### LINKED ISSUE #824: Add safe wallet dark mode support in the transaction builder
## Overview
Currently the transaction builder only supports the light mode theme, making a bad user experience for the users who has the dark mode active in the wallet, because they would be seeing dark in the wallet but white in the transaction builder screens.

## Requirements
Transaction builder should support dark mode.

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**
## What it solves
Resolves #824 

## How this PR fixes it
It adds dark mode theme palette into the project and set the theme based on the postMessage event which we receive from the safe wallet app.

## How to test it
- Go to your safe at this link: https://feat_tx_builder_dark_mode--walletweb.review.5afe.dev/home?safe=eth:0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6 (or by using this branch from the safe wallet repo: `feat/tx-builder-dark-mode`)
- Take the deploy link on this PR and add it as a custom safe app on your safe
- Open the custom tx-builder app which you just added
- Change the dark mode toggle on the sidebar
- The transaction builder theme should change according to safe wallet theme

## Video
[txbuilder.webm](https://github.com/user-attachments/assets/9a67645d-c61c-444b-8dfb-c2d15418a156)

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]

**Comment by francovenica** [comment]
Issues:

1 - The form when you edit a tx that is batched on the right side is still white:
image
image

2 - The list of saved batches show the list of them white as well:
For this you must save it in the library first: 
image

Go to Your tx library:
image

And then you see this:
image

**Comment by clovisdasilvaneto** [comment]
@francovenica thanks! I'll take a look on them

**Comment by clovisdasilvaneto** [comment]
@francovenica done ✅  Can you please check that again? Please make sure to clear your cache ;)

**Comment by francovenica** [comment]
I think the fixes broke some stuff in light mode now:

The saved batches, there is a number that should be white
There is a gray background that should be white
image
image

Same in the tx edition:
For the light mode there is a gray background when in dev is fully white. A comparison here:
image

in dev:
image

Also in the dark mode I think the whole modal should be gray. Compare it with any other tx in the site:

The tx edition in the tx builder:
image

A regular tx color:
image

**Comment by clovisdasilvaneto** [comment]
@francovenica can you please check that again?

**Comment by francovenica** [comment]
All the issues fixed
LGTM now.

**Pull request merged**
